version: '3.8'
services:
  backend:
    build:
      context: ./
      dockerfile: backend/Dockerfile
    ports:
      - '8000:8000'
    volumes:
      - ./backend/app:/app/app
    environment:
      - PYTHONUNBUFFERED=1
  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./:/app
    command: sh -c "npm install --no-audit --no-fund && npm run dev -- --host 0.0.0.0"
    ports:
      - '5173:5173'
    environment:
      - CHOKIDAR_USEPOLLING=true
      - VITE_API_BASE=http://host.docker.internal:8000/api
