// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hqlwvkfwvjaufedusncl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhxbHd2a2Z3dmphdWZlZHVzbmNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgwMzkzMTksImV4cCI6MjA3MzYxNTMxOX0.VZvZZrvVWXQhVbWxqkyBTAbdT5wcv0TCR20zcmktfYA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});