name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Set Node options for tests
        run: |
          echo "NODE_OPTIONS=--no-experimental-fetch" >> $GITHUB_ENV
      - name: Install dependencies
        run: npm ci
      - name: Typecheck
        run: npx tsc --noEmit
      - name: Lint
        run: npx eslint "src/**/*.{ts,tsx,js,jsx}" --max-warnings=0
      - name: Run tests
        run: npm test --if-present
      - name: Build frontend (optional)
        run: npm run build --if-present

  backend-smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install backend deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Start backend (background)
        run: |
          python -m uvicorn backend.app.main:app --port 8000 --host 127.0.0.1 &
          sleep 2
      - name: Wait for backend health
        run: |
          for i in 1 2 3 4 5; do
            if curl -sSf http://127.0.0.1:8000/api/health; then
              echo ok; exit 0
            fi
            sleep 1
          done
          exit 1
