name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  frontend-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install dependencies
        run: npm ci
      - name: Typecheck
        run: npx tsc --noEmit
      - name: Lint
        run: npx eslint "src/**/*.{ts,tsx,js,jsx}" --max-warnings=0
      - name: Run tests
        run: npm test --if-present

  backend-smoke:
    runs-on: ubuntu-latest
    services: {}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install backend deps
        run: |
          python -m pip install --upgrade pip
          pip install -r backend/requirements.txt
      - name: Run backend (uvicorn) in background
        run: nohup uvicorn backend.app.main:app --port 8000 &
      - name: Wait for backend
        run: |
          for i in {1..10}; do
            if curl -sSf http://127.0.0.1:8000/api/health; then
              echo ok; exit 0; fi; sleep 1;
          done; exit 1name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install deps
        run: npm ci
      - name: Build frontend
        run: npm run build

  build-backend:
    runs-on: ubuntu-latest
    services: {}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install backend deps
        run: python -m pip install -r backend/requirements.txt
      - name: Lint Python (basic)
        run: python -m pyflakes backend || true
      - name: Smoke run
        run: |
          uvicorn backend.app.main:app --port 8000 --host 127.0.0.1 &
          sleep 2
          curl -sSf http://127.0.0.1:8000/api/health
